apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
  namespace: default
spec:
  containers:
  - name: webapp
    image: kodekloud/simple-webapp-mysql
    resources:
      limits:
        cpu: "50m"
        memory: "100Mi"
      requests:
        cpu: "50m"
        memory: "100Mi"
    env:
      -name: MONGO_INIT_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              value: mongo-root-username
      -name: MONGO_INIT_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              value: mongo-root-password
